import { useCallback, useState } from 'react'
import { Clock3, MapPinned, PackageCheck, RefreshCw, Route, Store, Truck, Pause, Play, RotateCcw, Crosshair, Maximize2 } from 'lucide-react'
import RouteMap from '../../components/logistics/RouteMap'
import RouteComparisonCard from '../../components/logistics/RouteComparisonCard'
import Button from '../../components/ui/Button'
import Modal from '../../components/ui/Modal'
import { getStopOrders, logisticsCounts, logisticsStops, routeComparison, totalRouteQuantityKg } from '../../data/logistics'

const STATUS = { calculating: ['Calculating route...', 'bg-amber-100 text-amber-500'], ready: ['Route ready', 'bg-leaf-100 text-forest-700'], 'directions-error': ['Live Map • Demo Routing', 'bg-amber-100 text-amber-500'], unavailable: ['Google Maps unavailable — demo mode', 'bg-ink-100 text-ink-700'] }

export default function LogisticsDashboard() {
  const [selectedStopId, setSelectedStopId] = useState('kolar')
  const [routeState, setRouteState] = useState({ status: 'calculating' })
  const [refreshToken, setRefreshToken] = useState(0)
  const [detailsOpen, setDetailsOpen] = useState(false)
  const [tracking, setTracking] = useState(false)
  const [trackingState, setTrackingState] = useState({ progress: 0, currentStopId: 'kolar' })
  const [viewAction, setViewAction] = useState('')
  const onRouteState = useCallback((next) => setRouteState(next), [])
  const onSelectStop = useCallback((id) => setSelectedStopId(id), [])
  const onTrackingUpdate = useCallback((next) => { setTrackingState(next); setSelectedStopId(next.currentStopId) }, [])
  const [statusText, statusClass] = STATUS[routeState.status] || STATUS.calculating
  const selectedStop = logisticsStops.find((stop) => stop.id === selectedStopId)
  const currentStopIndex = logisticsStops.findIndex((stop) => stop.id === trackingState.currentStopId)
  const nextStop = logisticsStops[Math.min(currentStopIndex + 1, logisticsStops.length - 1)]
  const summary = routeState.status === 'ready' ? [`${routeState.distance} total distance`, `${routeState.duration} estimated travel time`] : ['Route estimates appear when Google Directions is available', 'Prototype route simulation remains available offline']

  return <div className="space-y-5">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="font-display text-xl font-bold text-ink-900">Today’s consolidated run</h2><p className="text-sm text-ink-500 mt-1">Kolar → Chikkaballapur → Tumakuru → Bengaluru deliveries</p></div><span className={`inline-flex items-center gap-2 rounded-full px-3 py-1.5 text-xs font-semibold ${statusClass}`}><i className="h-2 w-2 rounded-full bg-current" />{statusText}</span></div>

    <div className="grid grid-cols-2 lg:grid-cols-5 gap-3">
      <Kpi icon={Truck} label="Today’s Run" value="1 route" /><Kpi icon={PackageCheck} label="Orders" value={`${logisticsCounts.orders}`} /><Kpi icon={MapPinned} label="Stops" value={`${logisticsCounts.stops}`} /><Kpi icon={Store} label="FPOs" value={`${logisticsCounts.fpos}`} /><Kpi icon={Route} label="Buyers" value={`${logisticsCounts.buyers}`} />
    </div>

    <div className="grid lg:grid-cols-[minmax(0,2.1fr)_minmax(300px,0.9fr)] gap-5">
      <section className="card p-3 sm:p-4"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><div><h3 className="font-display font-semibold text-sm text-ink-900">Route map</h3><p className="text-xs text-ink-500">Road route is calculated from Google Directions when available.</p></div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => setViewAction(`recenter-${Date.now()}`)}><Crosshair size={14} /> Recenter</Button><Button size="sm" variant="outline" onClick={() => setViewAction(`fit-${Date.now()}`)}><Maximize2 size={14} /> Fit stops</Button><Button size="sm" variant="outline" onClick={() => setRefreshToken((value) => value + 1)}><RefreshCw size={14} /> Recalculate</Button><Button size="sm" onClick={() => setDetailsOpen(true)}>View details</Button></div></div><RouteMap selectedStopId={selectedStopId} onSelectStop={onSelectStop} onRouteState={onRouteState} refreshToken={refreshToken} tracking={tracking} onTrackingUpdate={onTrackingUpdate} viewAction={viewAction} /><div className="mt-3 grid sm:grid-cols-2 gap-2 text-xs">{summary.map((item) => <div key={item} className="flex items-center gap-2 rounded-lg bg-leaf-50 px-3 py-2 text-forest-800"><Clock3 size={13} />{item}</div>)}</div></section>
      <aside className="space-y-4"><div className="card p-4"><h3 className="font-display font-semibold text-sm text-ink-900">Route summary</h3><div className="mt-3 space-y-3"><Metric label="Total distance" value={routeState.status === 'ready' ? routeState.distance : routeState.status === 'directions-error' ? 'Demo polyline' : 'Route API pending'} /><Metric label="Estimated travel time" value={routeState.status === 'ready' ? routeState.duration : routeState.status === 'directions-error' ? 'Live road routing unavailable' : 'Route API pending'} /><Metric label="Stops · orders" value={`${logisticsCounts.stops} · ${logisticsCounts.orders}`} /><Metric label="Total quantity" value={`${totalRouteQuantityKg.toLocaleString('en-IN')} kg`} /></div></div><div className="card p-4"><div className="flex justify-between"><h3 className="font-display font-semibold text-sm">FarmLink Truck 01</h3><span className="text-[10px] font-bold text-clay-500">● DEMO LIVE</span></div><p className="mt-1 text-xs text-ink-500">Simulated vehicle motion — not GPS data.</p><p className="mt-3 text-sm font-medium text-ink-900">Current: {logisticsStops.find((stop) => stop.id === trackingState.currentStopId)?.name}</p><p className="text-xs text-ink-500">Next: {nextStop?.name} · {trackingState.remainingKm ?? '—'} km remaining</p><p className="text-xs text-ink-500">Progress {trackingState.progress}% · ETA {routeState.status === 'ready' ? routeState.duration : 'demo estimate'}</p><div className="mt-3 h-2 overflow-hidden rounded-full bg-ink-100"><div className="h-full bg-forest-600 transition-all duration-700" style={{ width: `${trackingState.progress}%` }} /></div><div className="mt-3 flex gap-2"><Button size="sm" onClick={() => setTracking((value) => !value)} disabled={!['ready', 'directions-error'].includes(routeState.status)}>{tracking ? <><Pause size={13} /> Pause</> : <><Play size={13} /> Start Demo</>}</Button><Button size="sm" variant="outline" onClick={() => { setTracking(false); setTrackingState({ progress: 0, currentStopId: 'kolar', remainingKm: routeState.distance }); setSelectedStopId('kolar') }}><RotateCcw size={13} /> Reset</Button></div></div><RouteComparisonCard baseline={routeComparison.baseline} optimized={routeComparison.optimized} /><StopSelector selectedId={selectedStopId} onSelect={onSelectStop} /></aside>
    </div>
    <div className="card p-4 flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><h3 className="font-display font-semibold text-sm text-ink-900">Order consolidation</h3><p className="mt-1 text-sm text-ink-700">{logisticsCounts.orders} demo orders from {logisticsCounts.fpos} FPOs are grouped for {logisticsCounts.buyers} Bengaluru buyers.</p></div><Button variant="secondary" onClick={() => setDetailsOpen(true)}>Open Route Details</Button></div>
    <p className="text-[11px] text-ink-400">Prototype route simulation — fixed stop order and comparison figures are demonstration values.</p>
    <RouteDetailsDrawer open={detailsOpen} onClose={() => setDetailsOpen(false)} selectedStop={selectedStop} onSelect={onSelectStop} />
  </div>
}

function Kpi({ icon: Icon, label, value }) { return <div className="card p-3 flex items-center gap-3"><div className="h-9 w-9 rounded-lg bg-leaf-50 text-forest-700 grid place-items-center"><Icon size={17} /></div><div><p className="text-[11px] text-ink-500">{label}</p><p className="font-display font-bold text-sm text-ink-900">{value}</p></div></div> }
function Metric({ label, value }) { return <div className="flex justify-between gap-3 text-sm"><span className="text-ink-500">{label}</span><span className="font-semibold text-ink-900 text-right">{value}</span></div> }
function StopSelector({ selectedId, onSelect }) { return <div className="card p-4"><h3 className="font-display font-semibold text-sm text-ink-900">Stops</h3><div className="mt-2 space-y-1">{logisticsStops.map((stop) => <button key={stop.id} onClick={() => onSelect(stop.id)} className={`w-full flex items-center gap-2 rounded-lg px-2.5 py-2 text-left text-xs ${selectedId === stop.id ? 'bg-leaf-50 text-forest-800' : 'hover:bg-sand-100 text-ink-700'}`}><span className={`grid h-5 w-5 place-items-center rounded-full text-[10px] font-bold text-white ${stop.type === 'pickup' ? 'bg-clay-500' : 'bg-forest-700'}`}>{stop.sequence}</span><span className="min-w-0 truncate font-medium">{stop.name}</span><span className="ml-auto text-ink-500">{stop.eta}</span></button>)}</div></div> }
function RouteDetailsDrawer({ open, onClose, selectedStop, onSelect }) { return <Modal open={open} onClose={onClose} title="Today’s route details" maxWidth="max-w-2xl"><p className="mb-4 text-xs text-ink-500">Prototype route simulation · fixed stop sequence</p><div className="space-y-3">{logisticsStops.map((stop) => { const orders = getStopOrders(stop); const quantity = orders.reduce((sum, order) => sum + order.quantityKg, 0); return <button key={stop.id} onClick={() => onSelect(stop.id)} className={`w-full rounded-xl border p-3.5 text-left transition-colors ${selectedStop?.id === stop.id ? 'border-forest-600 bg-leaf-50' : 'border-ink-100 hover:border-forest-400'}`}><div className="flex justify-between gap-3"><div><p className="text-xs font-bold text-forest-700">STOP {stop.sequence} · {stop.type === 'pickup' ? 'PICKUP' : 'DELIVERY'}</p><p className="mt-1 font-display font-semibold text-ink-900">{stop.name}</p><p className="text-xs text-ink-500">{stop.location} · ETA {stop.eta}</p></div><span className="h-fit rounded-md bg-white px-2 py-1 text-xs font-semibold text-ink-700">{stop.status}</span></div><div className="mt-3 grid sm:grid-cols-3 gap-2 text-xs"><Detail label="Orders" value={orders.length ? orders.map((order) => order.id).join(', ') : 'Consolidated delivery'} /><Detail label="Produce" value={orders.length ? orders.map((order) => order.product).join(', ') : 'Mixed load'} /><Detail label="Quantity" value={orders.length ? `${quantity} kg` : '—'} /></div></button> })}</div></Modal> }
function Detail({ label, value }) { return <div><p className="text-ink-500">{label}</p><p className="mt-0.5 font-medium text-ink-900">{value}</p></div> }
