import { useMemo, useState } from 'react'
import { Area, AreaChart, CartesianGrid, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { BarChart3, ClipboardList, Lightbulb, Package, Plus, TrendingUp, Wallet } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { useApp } from '../../context/AppContext'
import StatCard from '../../components/ui/StatCard'
import Badge, { demandTone } from '../../components/ui/Badge'
import Button from '../../components/ui/Button'
import { formatDate, formatINR } from '../../utils/format'
import { farmerForecast, farmerPriceSeries, nearbyMarketPrices } from '../../data/farmerDashboard'

export default function FarmerDashboard() {
  const { user, listings, orders } = useApp(); const navigate = useNavigate(); const [crop, setCrop] = useState('Tomato')
  const myProducts = listings.filter((p) => p.farmerId === user.id); const myOrders = orders.filter((o) => o.farmerId === user.id)
  const active = myOrders.filter((o) => o.stage !== 'Delivered'); const sales = myOrders.reduce((sum, o) => sum + o.total, 0); const pending = active.reduce((sum, o) => sum + o.total, 0)
  const stockValue = myProducts.reduce((sum, p) => sum + p.quantity * p.price, 0); const forecastValue = myProducts.reduce((sum, p) => sum + p.quantity * (p.name === 'Tomato' ? farmerForecast.predicted : p.price), 0)
  const prices = farmerPriceSeries[crop]; const current = prices.at(-2).price; const prediction = prices.at(-1).price; const change = ((prediction - prices[0].price) / prices[0].price * 100).toFixed(1)
  const shownOrders = myOrders.slice(0, 5)
  return <div className="space-y-5">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-forest-700">Farmer workspace</p><h2 className="font-display text-xl font-bold text-ink-900">Good morning, {user.name.split(' ')[0]}</h2><p className="mt-1 text-sm text-ink-500">A clear view of today’s farm sales, stock and market signals.</p></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => navigate('/farmer/orders')}><ClipboardList size={14} /> View Orders</Button><Button size="sm" onClick={() => navigate('/farmer/listing/new')}><Plus size={14} /> Add Listing</Button></div></div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><StatCard label="Total Sales" value={formatINR(sales)} icon={Wallet} sub="Demo order value" /><StatCard label="Active Orders" value={active.length} icon={ClipboardList} tone="amber" /><StatCard label="Produce Listed" value={myProducts.length} icon={Package} /><StatCard label="Pending Payments" value={formatINR(pending)} icon={Wallet} tone="clay" /></div>
    <div className="grid xl:grid-cols-[.9fr_1.4fr] gap-5"><ForecastCard onInsights={() => navigate('/farmer/insights')} /><PriceChart crop={crop} setCrop={setCrop} prices={prices} current={current} prediction={prediction} change={change} /></div>
    <div className="grid xl:grid-cols-[1.45fr_.85fr] gap-5"><ProduceCard products={myProducts} /><MarketCard /></div>
    <div className="grid xl:grid-cols-[1.45fr_.85fr] gap-5"><RecentOrders orders={shownOrders} /><div className="space-y-5"><HarvestValue value={stockValue} forecastValue={forecastValue} /><QuickActions navigate={navigate} /></div></div>
  </div>
}

function ForecastCard({ onInsights }) { const f = farmerForecast; return <div className="card p-5 bg-forest-900 border-none text-white"><div className="flex justify-between gap-3"><div><p className="text-[11px] font-bold tracking-wide text-leaf-300">AI DEMO PREDICTION</p><h3 className="mt-1 font-display text-lg font-bold">{f.crop} market forecast</h3></div><Badge tone="high">{f.demand} demand</Badge></div><div className="mt-5 grid grid-cols-3 gap-3"><MetricDark label="Current" value={`₹${f.current}/kg`} /><MetricDark label="Next 7 days" value={`₹${f.predicted}/kg`} /><MetricDark label="Confidence" value={`${f.confidence}%`} /></div><p className="mt-4 text-sm leading-relaxed text-leaf-100">Tomato demand is expected to rise over the next 7 days due to local market demand. Recommended listing quantity: {f.quantity} kg.</p><div className="mt-4 flex items-center justify-between"><span className="text-xs text-leaf-300">Expected change +{f.change}% · Prototype prediction</span><Button size="sm" variant="secondary" onClick={onInsights}><Lightbulb size={14} /> View AI Insights</Button></div></div> }
function MetricDark({ label, value }) { return <div><p className="text-[11px] text-leaf-300">{label}</p><p className="mt-1 font-display font-bold">{value}</p></div> }
function PriceChart({ crop, setCrop, prices, current, prediction, change }) { return <div className="card p-5"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-display font-semibold text-sm text-ink-900">7-day price trend</h3><p className="text-xs text-ink-500 mt-1">Prototype market data · final point is a demo prediction.</p></div><div className="flex gap-1 rounded-lg bg-sand-100 p-1">{Object.keys(farmerPriceSeries).map((name) => <button key={name} onClick={() => setCrop(name)} className={`rounded-md px-2.5 py-1 text-xs font-medium ${crop === name ? 'bg-white text-forest-700 shadow-sm' : 'text-ink-500'}`}>{name}</button>)}</div></div><div className="mt-3 flex gap-5 text-sm"><span><b className="text-ink-900">₹{current}</b><small className="ml-1 text-ink-500">current/kg</small></span><span><b className="text-forest-700">+{change}%</b><small className="ml-1 text-ink-500">7-day</small></span><span><b className="text-forest-700">₹{prediction}</b><small className="ml-1 text-ink-500">predicted</small></span></div><ResponsiveContainer width="100%" height={210}><AreaChart data={prices} margin={{ top: 20, left: -20, right: 8 }}><defs><linearGradient id="priceFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#4f9d5c" stopOpacity=".28"/><stop offset="1" stopColor="#4f9d5c" stopOpacity="0"/></linearGradient></defs><CartesianGrid vertical={false} stroke="#ecefeb"/><XAxis dataKey="day" tick={{ fontSize: 10, fill: '#6b756e' }} axisLine={false} tickLine={false}/><YAxis tick={{ fontSize: 10, fill: '#6b756e' }} axisLine={false} tickLine={false}/><Tooltip formatter={(value) => [`₹${value}/kg`, 'Price']} /><Area type="monotone" dataKey="price" stroke="#256e41" strokeWidth={2.5} fill="url(#priceFill)" /></AreaChart></ResponsiveContainer></div> }
function ProduceCard({ products }) { return <div className="card p-5"><div className="flex justify-between"><div><h3 className="font-display font-semibold text-sm text-ink-900">My produce</h3><p className="text-xs text-ink-500 mt-1">Live listing inventory · demo marketplace data</p></div><Package size={18} className="text-forest-600"/></div><div className="mt-4 space-y-3">{products.map((p) => <div key={p.id} className="rounded-xl border border-ink-100 p-3"><div className="flex items-center gap-3"><img src={p.image} alt="" className="h-11 w-11 rounded-lg object-cover"/><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><p className="font-medium text-sm text-ink-900">{p.name}</p><Badge tone={demandTone(p.demand)}>{p.demand}</Badge></div><p className="text-xs text-ink-500">{p.quantity.toLocaleString('en-IN')} {p.unit} · ₹{p.price}/{p.unit} · Value {formatINR(p.quantity * p.price)}</p><div className="mt-2 h-1.5 rounded-full bg-ink-100"><div className="h-full rounded-full bg-forest-600" style={{ width: `${Math.min(100, p.quantity / 10)}%` }}/></div></div></div></div>)}</div></div> }
function MarketCard() { return <div className="card p-5"><h3 className="font-display font-semibold text-sm text-ink-900">Nearby market prices</h3><p className="text-xs text-ink-500 mt-1">Prototype market data · ₹/kg</p><div className="mt-4 space-y-3">{nearbyMarketPrices.map((m) => <div key={m.market} className={`rounded-lg p-2.5 ${m.reference ? 'bg-leaf-50 border border-leaf-100' : 'bg-sand-50'}`}><div className="flex justify-between text-sm"><span className="font-medium text-ink-900">{m.market}{m.reference && <small className="ml-1 text-forest-700">Reference</small>}</span><span className="text-ink-500">Tomato ₹{m.tomato} · Chilli ₹{m.chilli}</span></div></div>)}</div></div> }
function RecentOrders({ orders }) { return <div className="card overflow-hidden"><div className="p-5 pb-3"><h3 className="font-display font-semibold text-sm text-ink-900">Recent orders</h3><p className="text-xs text-ink-500 mt-1">Orders for your listed produce</p></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="bg-sand-100 text-left text-xs text-ink-500"><th className="px-4 py-3">Order</th><th className="px-4 py-3">Buyer</th><th className="px-4 py-3">Product</th><th className="px-4 py-3">Qty</th><th className="px-4 py-3">Amount</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Date</th></tr></thead><tbody>{orders.map((o) => <tr key={o.id} className="border-t border-ink-100"><td className="px-4 py-3 font-medium">{o.id}</td><td className="px-4 py-3">{o.buyer}</td><td className="px-4 py-3">{o.product}</td><td className="px-4 py-3">{o.quantity} {o.unit}</td><td className="px-4 py-3">{formatINR(o.total)}</td><td className="px-4 py-3"><Badge tone={o.stage === 'Delivered' ? 'success' : 'medium'}>{o.stage}</Badge></td><td className="px-4 py-3 text-ink-500">{formatDate(o.placedOn)}</td></tr>)}</tbody></table></div></div> }
function HarvestValue({ value, forecastValue }) { return <div className="card p-5"><p className="text-xs font-bold tracking-wide text-forest-700">HARVEST VALUE</p><h3 className="mt-1 font-display font-semibold text-ink-900">Your current stock value</h3><p className="mt-3 font-display text-2xl font-bold text-ink-900">{formatINR(value)}</p><div className="mt-3 flex justify-between text-xs"><span className="text-ink-500">Potential at AI demo price</span><span className="font-semibold text-forest-700">{formatINR(forecastValue)}</span></div></div> }
function QuickActions({ navigate }) { return <div className="card p-5"><h3 className="font-display font-semibold text-sm text-ink-900">Quick actions</h3><div className="mt-3 grid gap-2"><Button variant="secondary" onClick={() => navigate('/farmer/listing/new')}><Plus size={14}/> Add New Listing</Button><Button variant="outline" onClick={() => navigate('/farmer/orders')}><ClipboardList size={14}/> View Orders</Button><Button variant="outline" onClick={() => navigate('/farmer/insights')}><BarChart3 size={14}/> AI Market Insights</Button></div></div> }
